# .github/workflows/deploy.yml
name: Deploy Docker Image

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Pull Docker image
      run: docker pull hamzabinriaz/your-image-name:latest
    
    - name: Stop and remove existing container if it exists
      run: |
        if [ $(docker ps -q -f name=your-container) ]; then
          docker stop your-container
          docker rm your-container
        fi
    
    - name: Run Docker container
      run: docker run -d --name your-container -p 8080:80 yourdockerhubusername/yourimagename:latest
