name: CI to Docker Hub

on:
  push:
    branches:
      - master  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Adjust this according to your .NET Core version

    - name: Build .NET Core API
      run: dotnet build --configuration Release

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t hamzabinriaz/your-image-name:latest .
        docker push hamzabinriaz/your-image-name:latest
